### PR TITLE
C++ front end fixes pr1

### PR DESCRIPTION
**Pull request by andreast271**
My branch is rebased on the current develop branch of diffblue/cbmc in order to remove merge conflicts. It also contains some changes to use the new symbol_table interface methods.

### CODE REVIEW

**Comment by tautschnig** [comment]
What's the plan here?

**Comment by andreast271** [comment]
I closed the pull request, because some changes in diffblue/cbmc have broken cbmc for C++. These need to be resolved first.

**Comment by tautschnig** [comment]
Ok; I'm aware of the issue about macros that you've filed. Any others?

**Comment by andreast271** [comment]
The removal of partial inlining. Daniel replaced that with instrument_preconditions, and that code does not work for C++. I don't know the details yet, since I only found the responsible commit an hour ago. But even on very simple C++ cbmc gives incorrect results. I suspect that assigning values to function parameters is being removed somewhere.

**Comment by andreast271** [comment]
Is there a reason why the regression tests contain very few simple end-to-end tests? I.e. something to test the general flow of data through cbmc, rather than a specific feature. Any one of those would have caught the problem earlier.

**Comment by tautschnig** [comment]
"regression tests" by definition should guard against regressions, and should thus focus on particular bits that were broken; you might indeed add some tests that prove how broken the current state of affairs is?

**Comment by andreast271** [comment]
cbmc-cpp isn't even running as part of the regression. Is that deliberate? It also contains only one test case, which currently passes vacuously.

**Pull request closed without merging**
